# Site
title:              Ricardo da Verdade Silva
bio:                .Net Pro | Ruby Enthusiast | Python Lover. Lazy programmer. I'm always learning more to write less. Also dad of two gorgeous dog (all dogs are gorgeous at all)
description:        ".Net Pro | Ruby Enthusiast | Python Lover. Lazy programmer. I'm always learning more to write less. Also dad of two gorgeous dog (all dogs are gorgeous at all)"
reading_time:       true
words_per_minute:   200
logo:               'assets/img/eu e charlinho.jpg'
#background:         'assets/img/placeholder-big.jpg'
tiled_bg:           true   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             pt_BR
#url:                https://www.ricardovsilva.com.br

blog_pages:
  - 

# Jekyll
permalink:          pretty
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Dependencies
highlighter:      rouge

# Comments
disqus_shortname:   ricardovsilva

#General
show_navbar: false

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:              ricardovsilva@msn.com
twitter:            MrTruthDev
facebook:           ricardovsilva91
github-url:         ricardovsilva
stackoverflow:      2350913/ricardo-silva
linkedin:           ricardo-silva-66067327
#xing:              username
#instagram:         username
lastfm:            ricardovsilva
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
steam:              ricardioS2
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username
twitch:             ricardioS2

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]

paginate:         5
paginate_path: "blog/page:num/"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ricardovsilva/ricardovsilva.github.io
