# Site settings
title: Mr Truth Development
email: ricardovsilva@msn.com
description: > # this means to ignore newlines until "baseurl:"
  Dicas e tutoriais destinados a todos que desejam entrar ou dar um salto
  no mercado de trabalho de desenvolvimento de software.
  Esta é minha tentativa de devolver um pouco de tudo o que a comunidade
  opensource já me deu.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ricardovsilva.github.io" # the base hostname & protocol for your site
twitter_username: MrTruthDev
github_username:  ricardovsilva

# Build settings
markdown: kramdown
paginate: 4
author: Ricardo da Verdade Silva
gems: [jekyll-paginate]
lang: pt-BR
